crawler:
  image: vitecde/metadata-crawler
  volumes:
    - ./myDir:/crawler/videos
  links: 
   - rabbitService
  environment:
    - API_KEY=your_own_api_key
    - Q_PASSWORD=user_name
    - Q_USER=user_password
    - Q_NAME=queue_name
    - Q_PORT=5672
    - Q_IP=rabbitService
  entrypoint: ./start_crawler.sh "SEARCH"
rabbitService:
   image: vitecde/rabbitmq-service
   ports:
   - "5672:5672"
   - "15672:15672"
