crawler:
   image: vitecde/metadata-crawler
   volumes:
     - /c/Users/mchavarria.COMO-INTRA/workspace/myDocker:/crawler/videos
   links: 
    - rabbitService
   environment:
     - API_KEY=you_own_API_Key
     - Q_PASSWORD=guest
     - Q_USER=guest
     - Q_NAME=crawlerQueue
     - Q_PORT=5672
     - Q_IP=rabbitService

rabbitService:
    image: vitecde/rabbitmq-service
    ports:
    - "5672:5672"
    - "15672:15672"
